# Use root/example as user/password credentials
version: '3.1'

services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "passwordroot"
            MYSQL_DATABASE: "pocarquitecturedb"
            MYSQL_USER: "pocarquitectureuser"
            MYSQL_PASSWORD: "pocarquitecturepass"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    adminer:
       image: adminer
       restart: always
       ports:
           - 8080:8080
    redis:
       image: redis:alpine
       ports:
           - 6379:6379